name: Denizen
author: aufdemrand
version: 0.1
main: net.aufdemrand.denizen.Denizen
depend:
  - Citizens
commands:
  denizen:
    description: Lists denizen commands.
    usage: /denizen help
    permission: mimic.basic
