# DENIZENS are helpful, interactive Citizens!  Denizens run off of mini scripts with steps and events.
# They can be used in hundreds of different ways, from tutorials, to questing, to administrating and more!

# Timeline: Beta 1 -- All functionality used in this example file.
#           Beta 2 -- Complete functionality of additional behaviors/requirements/triggers listed.
#           1.0 -- Bug fixes from Beta.
#           1.5 -- In-game Script editor.


# Default Denizen options let you tweak the specifics of your Denizens.

debug_mode: true
interact_delay_in_ticks: 20       #  Delay in ticks for all responses from the Denizens.  20 is default because it
                                  #  provides a good realistic delay when interacting with an NPC. Long texts and
                                  #  script events roll in to the player at a comfortable rate.
                                  #  It's not a good idea to set this any lower than 10!
npc_chat_range_in_blocks: 10      #  Range in blocks that the any player has to be to hear CHAT from an NPC.
player_chat_range_in_blocks: 2    #  Range in blocks that the player has to be to trigger chat with the NPC.
engage_timeout_in_seconds: 15     #  Default amount of time that the Denizen will automatically DISENGAGE

player_chat_to_npc: "You say to <NPC>, '<TEXT>'"
player_chat_to_npc_bystander: "<PLAYER> says to <NPC>, '<TEXT>'"
npc_chat_to_player: "<NPC> says to you, '<TEXT>'"
npc_chat_to_player_bystander: "<NPC> says to <PLAYER>, '<TEXT>'"
npc_whisper_to_player: "<NPC> whispers to you, '<TEXT>'"
npc_whisper_to_player_bystander: "<NPC> whispers something to <PLAYER>."
npc_shout_to_player: "<NPC> shouts at you, '<TEXT>'"
npc_shout_to_player_bystander: "<NPC> shouts at <PLAYER>, '<TEXT>'"

chat_color: white
whisper_color: gray
shout_color: red
narrate_color: green
announce_color: yellow

# START LIST OF DENIZENS

Denizens:                         
  'Steve':                        
    Scripts:                      
      - 0 Welcome to the Village  
      - 5 A pie delivered         
    Texts:                        
      No Scripts To Trigger: I have nothing to say to you at this time.
	  
Scripts:
  'Welcome to the Village':    
        
    Requirements:              
      Mode: All                
      List:                    
        - Time Day             

    Steps:                     
      '0':                     
 
        Interact:              

          Click Trigger:       
            - CHAT Welcome to our fair city, <player>!        
            - CHAT Are you traveling from out of town?
            - DELAY 2 
            - NARRATE <NPC> seems like a friendly face.

          Chat Trigger:        
            '0':               
              Trigger: 'Yes'   
              Script:
                - DELAY 2      
                - CHAT Oh! I'm sorry I didn't recognize you! 
                - CHAT Our small village is so small I almost feel embarrassed. I should have known you lived close by!
                - CHAT Have you heard about Tom the Tanner? Isn't that just the worst!?
                - ZAP 2        
            '1':
              Trigger: 'No'    
              Script:          
                - DELAY 2      
                - CHAT I didn't think I've seen you around these parts!
                - CHAT Well, welcome to the town of Chakkor! 
                - CHAT If you are looking for some work, I would check with James at the Bakery. This is their busy season!
                - ZAP          

          On Finish:           
                               
            - NARRATE What a friendly face.
            - NOTABLE Chat with a villager      

      '1':        
          Click Trigger:
            - CHAT Welcome back, <player>!          
            - CHAT Have you talked to James lately?

      '2':
          Click Trigger:
            - CHAT How is your day going, <player>! 
            - CHAT I wish there were something we could do for Tom!

  'A pie delivered':            
        
    Requirements:                 
      Mode: All                   
      List:                       
        - QUEST A Pie for Tom  

    Behavior:                  
      - Controlled                                               

    Progression:    
      '0':                        
        Interact:                   
          Click Trigger:  
            - CHAT Oh <player>! I heard what you did for Tom!
            - CHAT We're lucky to have people like you in our small village! 

Players:
  aufdemrand:      
    'Script Name':      
      Current Step: 0
      Completed: 4

Notables:
  Notables:
    "This Notable":
      Type: Achievement
	  Obtain Text: "You've obtained THIS NOTABLE!"
      Journal Entry: "Today I obtained THIS NOTABLE. It was a glorious day!"
      Flags:
        - Repeatable
  Players:
    aufdemrand:
      - This Notable, 4


      