name: Denizen
author: aufdemrand
version: 0.3
main: net.aufdemrand.denizen.Denizen
depend:
  - Citizens
  - Vault
commands:
  denizen:
    description: Lists denizen commands.
    usage: /denizen help
    permission: denizen.basic
