# Whether debug information about Denizen should appear in the
# server console

Debug:
  Show: true

# The default options for new Denizens

Scripts:
  Queue Speed: 0.5s
  Load Scripts in Subfolders: true

Traits:
  Health:
    Enabled: false
    Respawn:
      Enabled: true
      Delay: 10s

Triggers:
  Chat:
    Cooldown: 2s
    Range: 3
    Overhearing Range: 4
    Prerequisites:
      Must Be Able to See NPC: true
      Must Be Looking in Direction of NPC: true
    Formats:
      Player to NPC: "You -> <npc.name.nickname>: <text>"
      Player to NPC Overheard: "<player.name> -> <npc.name.nickname>: <text>"
    Appears Globally:
      If Triggers Missing: true
      If Triggers Failed: false
      If NPC Uninteractable: true
  Click:
    Cooldown: 2s
    Allows Left Click: false
  Damage:
    Cooldown: 0.5s
  Location:
    Cooldown: 5s
    Range: 2
  Proximity:
    Cooldown: 1s
    Range: 10

Commands:
  Engage:
    Timeout: 150s

# The version of this configuration file, used to check if your
# configuration file is outdated or too new

Config:
  Version: 1