name: Denizen
author: aufdemrand
version: 0.8-prerelease
main: net.aufdemrand.denizen.Denizen
depend: [Citizens]
softdepend: [Vault]

commands:
  denizen:
    description: Lists denizen commands.
    usage: /denizen help
    permission: denizen.basic
  notable:
    description: Lists notable commands.
    usage: /notable help
    permission: notable.basic
  flag:
    description: Lists flag commands.
    usage: /flag help
    permission: notable.basic

permissions:
  denizen.*:
    description: Gives access to Denizen commands
    children:
      denizen.basic: true