name: Denizen
author: aufdemrand
version: 0.7
main: net.aufdemrand.denizen.Denizen
depend: [Citizens]
softdepend: [Vault]

commands:
  denizen:
    description: Lists denizen commands.
    usage: /denizen help
    permission: denizen.basic

permissions:
  denizen.*:
    description: Gives access to Denizen commands
    children:
      denizen.basic: true